import assert from 'node:assert/strict';

export const doubleControl={ready:0x06a0,done:0x06a1,active:0x06a2,pending:0x06a3,expirations:0x06a4};
export function emitDoubleVideo(emitter,state,stage,template){
  const get=address=>emitter.abs(0xad,address,'read'),put=address=>emitter.abs(0x8d,address,'write');
  const set=(address,value)=>{emitter.emit(0xa9,value);put(address);};
  const vector=label=>{emitter.immediateAddress(0xa9,label,0);put(0xfffe);emitter.immediateAddress(0xa9,label,8);put(0xffff);};
  const enabled=0x02e3,streaming=0x02e4,control=doubleControl;
  const finish=[];
  for(let offset=0x1000;offset<0x1400;offset++)if(template[offset]===0x4c&&template[offset+1]===0x81&&template[offset+2]===0xea)finish.push(offset+0x2001);
  assert.equal(finish.length,2);
  const patchFinish=bank=>{for(const address of finish){emitter.immediateAddress(0xa9,'nuflix_irq_finish',0);put(address+bank);emitter.immediateAddress(0xa9,'nuflix_irq_finish',8);put(address+bank+1);}};
  emitter.label('mpe_video_packet');get(stage+6);emitter.emit(0xc9,3);emitter.jumpUnless(0xf0,'error_type');
  get(stage+9);emitter.emit(0xc9,2);emitter.jumpUnless(0xf0,'error_type');get(stage+10);emitter.emit(0xc9,16);emitter.jumpUnless(0xf0,'error_type');
  get(stage+8);emitter.emit(0xc9,3);emitter.jumpUnless(0xd0,'nuflix_stream');emitter.emit(0xc9,4);emitter.jumpUnless(0xd0,'nuflix_stream_done');
  emitter.emit(0xc9,1);emitter.branch(0xd0,'nuflix_resume');set(streaming,0);
  get(state.baseReady);emitter.branch(0xf0,'nuflix_pause_hidden');emitter.abs(0x20,'wait_fresh_border');
  emitter.label('nuflix_pause_hidden');emitter.emit(0x78);set(0xd01a,0);set(0xd015,0);set(0xd011,0x2b);
  for(const address of [control.ready,control.done,control.active,control.expirations])set(address,0);set(control.pending,255);
  emitter.emit(0xa2,5,0xa9,0);emitter.label('nuflix_clear_top_pointers');emitter.abs(0x9d,0xfff8);emitter.emit(0xca);emitter.branch(0x10,'nuflix_clear_top_pointers');emitter.abs(0x4c,'ack_packet');
  emitter.label('nuflix_resume');emitter.emit(0xc9,2);emitter.jumpUnless(0xf0,'error_type');emitter.emit(0x78);
  set(enabled,1);set(state.baseReady,1);set(state.transitionHidden,0);set(state.parserSplit,0);set(state.parserPhase,0);set(state.frameMode,8);
  get(0xdd02);emitter.emit(0x09,3);put(0xdd02);get(state.videoTiming);emitter.emit(0x8d,0xa6,0x02);vector('nuflix_irq_dispatch');patchFinish(0);
  const wait=template.readUInt16LE(0),end=[];
  for(let offset=0x1000;offset<0x1100;offset++)if(template[offset]===0x4c&&template.readUInt16LE(offset+1)===wait)end.push(offset+0x2000);
  assert.equal(end.length,1);set(end[0],0x60);emitter.abs(0x20,0x3000);
  emitter.abs(0x20,'wait_fresh_border');emitter.abs(0x20,'wait_fresh_border');emitter.abs(0x4c,'ack_packet');
  emitter.label('mpe_video_disable');get(enabled);emitter.branch(0xf0,'nuflix_disabled');emitter.abs(0x20,'wait_fresh_border');emitter.emit(0x08,0x78);
  set(streaming,0);set(enabled,0);set(control.pending,255);set(0xd015,0);set(0xd017,0);set(0xd01b,0);set(0xd01c,0);set(0xd01d,0);
  get(0xdd00);emitter.emit(0x29,0xfc,0x09,1);put(0xdd00);vector('raster_irq');set(0xd012,250);set(0xd011,0x3b);set(0xd018,0x08);set(0xd019,1);emitter.emit(0x28);
  emitter.label('nuflix_disabled');emitter.emit(0x60);
  emitter.label('nuflix_stream');get(enabled);emitter.jumpUnless(0xd0,'error_type');set(streaming,1);emitter.abs(0x4c,'ack_packet');
  emitter.label('nuflix_stream_done');set(streaming,0);get(control.active);emitter.branch(0x30,'nuflix_prepare_low');
  patchFinish(0x8000);emitter.emit(0xa2,39);emitter.label('nuflix_high_alias');emitter.abs(0xbd,0xa280);emitter.abs(0x9d,0x8280);emitter.emit(0xca);emitter.branch(0x10,'nuflix_high_alias');
  emitter.emit(0xa2,7);emitter.label('nuflix_high_pointers');emitter.abs(0xbd,0xa3f8);emitter.abs(0x9d,0x83f8);emitter.emit(0xa9,0xfe);emitter.abs(0x9d,0x87f8);emitter.emit(0xca);emitter.branch(0x10,'nuflix_high_pointers');
  emitter.emit(0xa9,0x80);emitter.abs(0x4c,'nuflix_publish_swap');
  emitter.label('nuflix_prepare_low');patchFinish(0);emitter.emit(0xa2,39);emitter.label('nuflix_low_alias');emitter.abs(0xbd,0x2280);emitter.abs(0x9d,0x0280);emitter.emit(0xca);emitter.branch(0x10,'nuflix_low_alias');
  emitter.emit(0xa2,7);emitter.label('nuflix_low_pointers');emitter.abs(0xbd,0x23f8);emitter.abs(0x9d,0x03f8);emitter.emit(0xa9,0xfe);emitter.abs(0x9d,0x07f8);emitter.emit(0xca);emitter.branch(0x10,'nuflix_low_pointers');
  emitter.emit(0xa9,0);emitter.label('nuflix_publish_swap');put(control.pending);
  emitter.label('nuflix_swap_wait');get(control.pending);emitter.emit(0xc9,255);emitter.branch(0xd0,'nuflix_swap_wait');emitter.abs(0x4c,'ack_packet');
  emitter.label('mpe_video_border_tick');get(streaming);emitter.branch(0xf0,'nuflix_border_done');
  get(0xd011);emitter.branch(0x30,'nuflix_border_done');get(0xd012);emitter.emit(0xc9,253);emitter.branch(0xb0,'nuflix_border_done');
  emitter.label('nuflix_border_wait');get(0xd012);emitter.emit(0xc9,251);emitter.branch(0x90,'nuflix_border_wait');
  set(control.done,0);set(0xdff4,5);set(1,0x34);set(control.ready,0xa5);emitter.emit(0xa2,32);
  emitter.label('nuflix_ram_wait');get(control.done);emitter.branch(0xd0,'nuflix_ram_close');emitter.emit(0xca);emitter.branch(0xd0,'nuflix_ram_wait');emitter.abs(0xee,control.expirations);
  emitter.label('nuflix_ram_close');set(control.ready,0);set(1,0x35);
  emitter.label('nuflix_border_done');emitter.emit(0x60);
  emitter.label('nuflix_irq_finish');emitter.abs(0xee,state.rasterTicks,'write');emitter.abs(0x20,'dos_fli_frame_ready');emitter.abs(0x20,'mpe_video_border_tick');
  get(control.pending);emitter.emit(0xc9,255);emitter.branch(0xf0,'nuflix_irq_done');put(control.active);
  get(state.videoTiming);emitter.branch(0xf0,'nuflix_swap_ntsc');get(control.active);emitter.emit(0x09,0x30);emitter.abs(0x4c,'nuflix_swap_vector');
  emitter.label('nuflix_swap_ntsc');get(control.active);emitter.emit(0x09,0x31);
  emitter.label('nuflix_swap_vector');emitter.emit(0x8d,0x15,0x03);set(control.pending,255);
  emitter.label('nuflix_irq_done');emitter.emit(0x68,0xa8,0x68,0xaa,0x68,0x40);
  emitter.label('nuflix_irq_dispatch');emitter.emit(0x48,0x8a,0x48,0x98,0x48,0xba,0xbd,0x04,0x01,0x29,0x10,0xf0,0x03,0x6c,0x16,0x03,0x6c,0x14,0x03);
  emitter.label('nuflix_irq_dispatch_end');
}
